title: Divya Hegde
logo: /assets/headshot.jpeg
description: |
  MS Data Science @ Northeastern University | ex-Salesforce | Gen-AI Product co-op @ The Burnes Center for Social Change 
  <br>
  <a href="mailto:divyahegdefte@gmail.com">ğŸ“§ Email</a> | 
  <a href="https://github.com/divyahegde-07">ğŸ™ GitHub</a> | 
  <a href="https://linkedin.com/in/hegdedivya">ğŸ’¼ LinkedIn</a>
#show_downloads: true
theme: jekyll-theme-minimal
email: "divyahegdefte@gmail.com"
alternate_email  : "hegde.di@northeastern.edu"
github: "divyahegde-07"
linkedin: "hegdedivya"


