title: Divya Hegde
logo: /assets/headshot.jpeg
description: |
  MS Data Science @ Northeastern University | ex-Salesforce | Gen-AI Product co-op @ The Burnes Center for Social Change |
  ğŸ“§ <a href="mailto:divyahegdefte@gmail.com">divyahegdefte@gmail.com</a><br>
  ğŸ™ <a href="https://github.com/divyahegde-07">GitHub</a><br>
  ğŸ’¼ <a href="https://linkedin.com/in/hegdedivya">LinkedIn</a>
#show_downloads: true
theme: jekyll-theme-minimal
email: "divyahegdefte@gmail.com"
alternate_email  : "hegde.di@northeastern.edu"
github: "divyahegde-07"
linkedin: "hegdedivya"
author:
  name: "Divya Hegde"
  avatar: "/assets/headshot.jpeg"
  bio: "MS Data Science @ Northeastern University | ex-Salesforce | Gen-AI Product co-op @ The Burnes Center for Social Change"
  location: "Boston, MA"
  email: "divyahegdefte@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:divyahegdefte@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/divyahegde-07"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/hegdedivya"

